#!/bin/sh

# autowifi v8.3
# Bruno "GNUser" Dantas GPLv3

# user variables:
iface=wlan0

main()
{
	start_fresh
	scan

	# SSIDs are searched in order, script connects to the first one found:
	ssid="AndroidAP"; password="PhonePassWord"; search && connect
	ssid="HomeSweetHome"; password="hoMepassworD"; search && connect
	ssid="OpenCafe"; password=""; search && connect

	# still here, so none of the above SSIDs were found:
	echo "No known hotspots within range."; exit
}

start_fresh()
{
	kill $(pgrep -f autowifi | grep -v $$) 2>/dev/null # kill other instances of this script
	pkill -f iw
	pkill -f wpa_supplicant
	pkill -f udhcpc
	ifconfig $iface down; ifconfig $iface up
}

scan()
{
	echo "Scanning available networks..."
	iw dev $iface scan flush > $scan_results
}

search()
{
	grep -q "$ssid" $scan_results && return 0 || return 1
}

connect()
{
	echo "Found ${ssid}, connecting..."

	if [ -z "$password" ]; then
		printf 'ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=root\nupdate_config=1\n' > $auth_file
		printf 'network={\n\tssid="%s"\n\tkey_mgmt=NONE\n}\n' $ssid >> $auth_file
	else
		printf 'ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=root\nupdate_config=1\n' > $auth_file
		wpa_passphrase "$ssid" "$password" >> $auth_file
	fi
	wpa_supplicant -i $iface -c $auth_file &

	sleep 3

	udhcpc -S -i $iface
	exit
}

# internal variables:
scan_results=/tmp/wifi-scan-results.txt
auth_file=/tmp/wifi.conf

main
