#!/bin/sh

# autowifi v5.1
# Bruno "GNUser" Dantas GPLv3

# user variables:
iface=wlan0
dhclient_config_file=/etc/dhcp/dhclient.conf

main()
{
	start_fresh
	scan

	# SSIDs are searched in order, script connects to the first one found:
	ssid="AndroidAP"; password="phoNePasswOrd"; search && connect
	ssid="homeSweetHome"; password="hoMepasswoRd"; search && connect
	ssid="openCafe"; password=""; search && connect

	# still here, so none of the above SSIDs were found:
	echo "No known hotspots within range."; exit
}

start_fresh()
{
	kill $(pgrep -f autowifi | grep -v $$) 2>/dev/null # kill other instances of this script
	pkill -f iwlist
	pkill -f wpa_supplicant
	pkill -f dhclient

	# restart the interface
	ifconfig $iface down
	ifconfig $iface up
}

scan()
{
	echo "Scanning available networks..."
	iwlist $iface scanning > $scan_results
}

search()
{
	grep -q "$ssid" $scan_results && return 0 || return 1
}

connect()
{
	echo "Found ${ssid}, connecting..."

	if [ -z "$password" ]; then
		printf 'network={\n\tssid="%s"\n\tkey_mgmt=NONE\n}\n' $ssid > $auth_file
	else
		wpa_passphrase "$ssid" "$password" > $auth_file
	fi
	wpa_supplicant -i $iface -c $auth_file &

	sleep 3

	dhclient -v -cf $dhclient_config_file $iface

	exit
}

# internal variables:
scan_results=/tmp/wifi-scan-results.txt
auth_file=/tmp/wifi.conf

main
